name: Ser2net
version: 1.0.10
slug: ser2net
description: Serial to Network Proxy
url: https://github.com/cfouche3005/addon-ser2net
arch:
  - amd64
  - armv7
  - aarch64
  - armhf
  - i386
startup: services
boot: auto
host_network: true
init: false
uart: true
udev: true
options:
  log_level: info
  connections: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|critical|alert|emergency)
  connections:
    - name: str
      port: int(1,65535)
      device: str
      baud: int
      parity: list(none|even|odd)
      stopbits: int(1,2)
      databits: int(5,8)
      max_connections: int(1,100)?
      kickolduser: bool?